apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-key
  namespace: chay-techs-production
spec:
  encryptedData:
    .dockerconfigjson: AgAqI39cjBijELl4ntMNRpqG2RL4d3xZHXGn0JBslblb8et5mZnMqXG9gemeSvWZQP7D8IYvSfpUxtdBIDEj9yf8kUfWj0ZNG6neJFZzlJlk2mU2zcF7/1QPxrFXECZ2uzJpUNx9zQ82wi+Gj7DxgabLClUiIyDvNTjbXqQmGUAEm3mJSaxrt1RplWCP1pYnI4hlfQE53PrqPU9nnXNZmjssW3ZeMOutuuCXWq6IGHFcurkSoGvRhcXw9LeOfXQD4Vul6unRAih127w4fPiSIBZJUysO9yjvcMgpe0ckg/y89s8ttc3WCt3sPCvys1LrIHY5t3LIx352RgAOBKStUcGQRoxQcT0HIAfPRLxxPsZAw2LrA3HFRo3T2xYFLoGn+Lnt0u9NUtrfQeHoEgFR3EmSJK8lp6n4h5Ym1ngbxAw5c+dEROcpDtKBF8fAv5pxSbnM9YtE5l+HvKZyvDX4QTPnAUJde3Ik0YT+Jxce74/6ZiopHdFsftirgECrgbd4mRKPAUkKo3OLu4zmj0oD9eI3GE2uzZA9LH4dWrmsbYj0NUH9gkZOwubhGoNaz8EK1qx+5AHohbi0u6lvn4WeVmbfC9ZK7UR4b4qrWG9KK3gYIxKIIsUOOfImniECvn0DG8LPHgkm7JkknVK6qkB1474c93Dv6uE7wcKqGQbR9nm73KOqHnz56XXUO2QRBokUvq4ov3sUGegAEQmOOwRricg0lfzwgOqz1xiybKnT3JL1GRooRAt9Z58fit2uFfReik9i+P7hToZrgfXjil3e8gvvYLHVl+6Q4OzNMFhq/Zlxa/e2lsyF
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-key
      namespace: chay-techs-production
    type: kubernetes.io/dockerconfigjson

